### ISSUE TITLE
Update Awards Pages

### ISSUE THREAD

**Issue by mngutterman** [col-bsa/Unami-Lodge-Documentation#1]
**Owner / Committee:**
Communications

**Due Date:**
1/8/2018

**Description:**
Update the [awards history pages](http://unamilodge.org/history-awards) on the lodge website.

**Tasks:** 
- [x] Richards Award
- [x] Benshetler Award
- [x] Fortunato Award
- [x] Founder's Award
- [x] Green Turtle Award

**Comment by crossfireprod** [comment]
PR created:
https://github.com/col-bsa/UnamiLodge.org/pull/36
