### ISSUE TITLE
Website - TOR

### ISSUE THREAD

**Issue by asterj** [col-bsa/Unami-Lodge-Documentation#10]
**Owner / Committee:**
Jeffrey Aster

**Due Date:**
ASAP

**Description:**
Change dates for TOR, now 10/19 & 10/20

**Tasks:** 
- [ ] Change dates on /tor 
- [ ] Update fliers... added to slack channel
- `https://drive.google.com/open?id=0BwyKy3ZKyreQZUh1cE8xbzdzc0F3TnZQX0VRX2J3S0xhYTBJ`
- `https://drive.google.com/open?id=0BwyKy3ZKyreQeFhZTXNGRGhZdTJORVBpXzVLNEFhS29kb1pR`

**Comment by crossfireprod** [comment]
Heads up @asterj, the markdown syntax for check-boxes is "[ ] Your text here."

https://guides.github.com/features/mastering-markdown/
