### ISSUE TITLE
Awards Social Media Campaign

### ISSUE THREAD

**Issue by dwgibbons** [col-bsa/Unami-Lodge-Documentation#12]
**Owner / Committee:**
Communications / Awards?

**Due Date:**
ASAP

**Description:**
Formulate social media campaign to announce award recipients

**Tasks:** 
- [ ] Plan campaign
- [ ] Post to website
- [ ] Schedule social media posts

**Comment by crossfireprod** [comment]
This is abandoned, closing issue.
