### ISSUE TITLE
Homepage Upcoming Events Padding

### ISSUE THREAD

**Issue by crossfireprod** [col-bsa/Unami-Lodge-Documentation#20]
**Owner / Committee:**

**Due Date:**

**Description:**
Padding isn't always respected around the upcoming events box.

**Tasks:** 
- [ ] 
- [ ] 
- [ ] 

![screenshot from 2018-04-07 15-30-58](https://user-images.githubusercontent.com/2859289/38459551-fe2486b4-3a78-11e8-9ecd-d94649d486fa.png)

**Comment by dwgibbons** [comment]
Fixing this is not worth the time.

**Comment by crossfireprod** [comment]
Agreed.  :(
