### ISSUE TITLE
Add 2018 Awards Recipients To Website

### ISSUE THREAD

**Issue by crossfireprod** [col-bsa/Unami-Lodge-Documentation#9]
**Owner / Committee:**
Communications

**Due Date:**
07Jan18

**Description:**
Add 2018 awards recipients (announced at the dinner) to the website.

**Tasks:** 
- [ ] Richards
- [ ] Benshetler
- [ ] Fortunato
- [ ] Founder's
- [ ] Green Turtle

**Comment by mngutterman** [comment]
Same as issue #1. Closing due to duplication.
